apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: logging-rule
  namespace: default
  labels:
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    - name: logging
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(logback_events_total{job="k8s-java-app-service", level="info"}[5m])) > 5
          labels:
            severity: warning
          annotations:
            summary: Info logging
            description: "{{ $labels.pod }} in namespace {{ $labels.namespace }} has INFO logs."
