apiVersion: v1
kind: Service
metadata:
  name: k8s-java-app-service
  namespace: default
spec:
  selector:
    app: k8s-java-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
  type: ClusterIP
